# ==================================== #
# AnarchyCORE - by Vesek and Matejko06 #
# VERSION 1.3.0                        #
# ==================================== #
# TPS message.
tps-message: "&6Server TPS is: "
# TPS color is from amount up to next color. #
tps-green: 16.00
tps-green-color: "&a&l"
tps-yellow: 8.00
tps-yellow-color: "&e&l"
tps-red-color: "&c&l"
# Help command #
help-message: "&3<----------------------->\n&6&o/help &3- Shows this.\n&6&o/kill &3- Kills the player.\n&6&o/tps &3- Shows server TPS.\n&6&o/info &3- Shows some info about the server.\n&6&o/priority &3or &6&o/queue &3- Shows players queue priority.\n&3<----------------------->"
# Suicide and Admin kill messages. #
kill-message: "&6You killed yourself!"
killsomeone-message: "&6You were killed!"
# Queue priority messages. #
queue-message: "&6Your queue priority is: "
regular-message: "&7&lRegular"
priority-message: "&6&lPriority"
admin-message: "&c&lAdmin"
# Invalid command message. #
invalid-command: "&4This command does not exist! Use &6/help&4 for help."
#Message for /info #
info-message: "&3Already <players> have connected to the server, server runs for <time> and world has <size> so far."
# If false, commands needs to set /tps and /help to /anarchycore:tps and /anarchycore:help in commands.yml. #
command-preprocessing:  true
# Join message #
join-message: "has joined!"
# Leave message #
leave-message: "has left!"
# f #