# ==================================== #
# AnarchyCORE - by Vesek and Matejko06 #
# VERSION 1.3.0                        #
# ==================================== #
kill-message: "&6You killed yourself!"
killsomeone-message: "&6You were killed!"
tps-message: "&6Server TPS is: "
# TPS color is from amount up to next color. #
tps-green: 16.00
tps-green-color: "&a&l"
tps-yellow: 8.00
tps-yellow-color: "&e&l"
tps-red-color: "&c&l"
# Queue priority messages. #
queue-message: "&6Your queue priority is: "
regular-message: "&7&lRegular"
priority-message: "&6&lPriority"
admin-message: "&c&lAdmin"
# Invalid command message. #
invalid-command: "&4This command does not exist! Use &6/help&4 for help."
#Message for /info #
info-message: "&3Already <players> have connected to the server, server runs for <time> and world has <size> so far."
# If false, commands needs to set /tps to /finshhim:tps in commands.yml. #
command-preprocessing:  true