name: AnarchyCORE
version: ${project.version}
main: org.matejko06.vesek.anarchycore.AnarchyCORE

commands:
  ac:
    description: AnarchyCORE.
    aliases: [acore]
  acversion:
    description: Shows plugin version.
    aliases: [acoreversion]
  acdiscord:
    description: Support Discord server.
    aliases: [acorediscord, acsupport, acoresupport]
  acreload:
    description: Reloads the plugin.
    aliases: [acorereload]
  help:
    description: Help for players.
  kill:
    description: Suicide.
    aliases: [suicide, killme]
  tps:
    description: Shows server TPS.
    aliases: [servertps]
  priority:
    description: Shows players priority in queue.
    aliases: [queuepriority]
  info:
    description: Shows info about the server.
    aliases: [serverinfo, serverstats, serverstatistics]
  togglechat:
    description: Toggles the chat.
    aliases: [chattoggle]
  toggledeathmsg:
    description: Toggles the death messages in chat.
    aliases: [deathmsgtoggle]
permissions:
  AnarchyCORE.*:
    children:
      AnarchyCORE.kill: true
      AnarchyCORE.togglechat: true
      AnarchyCORE.toggledeathmsg: true
      AnarchyCORE.help: true
      AnarchyCORE.tps: true
      AnarchyCOREQueue.admin: true
      AnarchyCORE.killSomeone: true
      AnarchyCORE.version: true
      AnarchyCORE.reload: true
      AnarchyCORE.discord: true
    default: false
  AnarchyCORE.priority:
    children:
      AnarchyCORE.kill: true
      AnarchyCORE.togglechat: true
      AnarchyCORE.toggledeathmsg: true
      AnarchyCORE.help: true
      AnarchyCORE.tps: true
      AnarchyCOREQueue.priority: true
      AnarchyCORE.killSomeone: false
      AnarchyCORE.version: false
      AnarchyCORE.reload: false
      AnarchyCORE.discord: false
    default: false
  AnarchyCORE.regular:
    children:
      AnarchyCORE.kill: true
      AnarchyCORE.togglechat: true
      AnarchyCORE.toggledeathmsg: true
      AnarchyCORE.help: true
      AnarchyCORE.tps: true
      AnarchyCOREQueue.regular: true
      AnarchyCORE.killSomeone: false
      AnarchyCORE.version: false
      AnarchyCORE.reload: false
      AnarchyCORE.discord: false
    default: true
  AnarchyCORE.togglechat:
    description: Allows player to use /togglechat.
  AnarchyCORE.toggledeathmsg:
    description: Allows player to use /toggledeathmsg.
  AnarchyCORE.help:
    description: Allows player to use /help.
    default: true
  AnarchyCORE.kill:
    description: Allows player to use /kill or /suicide.
    default: true
  AnarchyCORE.killSomeone:
    description: Allows player to use /kill on someone else.
    default: false
  AnarchyCORE.tps:
    description: Allows player to use /tps.
    default: true
  AnarchyCORE.queue.regular:
    description: Sets player priority level in queue.
    default: true
  AnarchyCORE.queue.priority:
    description: Sets player priority level in queue.
    default: false
  AnarchyCORE.queue.admin:
    description: Sets player priority level in queue.
    default: false
  AnarchyCORE.version:
    description: Allows player to use /acore version.
    default: false
  AnarchyCORE.reload:
    description: Allows player to reload the plugin.
    default: false
  AnarchyCORE.discord:
    description: Allows player to use /acorediscord.
    default: false