name: AnarchyCORE
version: ${project.version}
main: org.matejko06.vesek.anarchycore.AnarchyCORE

commands:
  acore:
    description: Acore.
    aliases: [ac]
  acversion:
    description: Shows plugin version.
    aliases: [acoreversion]
  help:
    description: Help for players.
  acadminhelp:
    description: Help for admin.
    aliases: [acoreadminhelp]
  acdiscord:
    description: Support Discord server.
    aliases: [acorediscord]
  acreload:
    description: Reloads the plugin.
    aliases: [acorereload]
  kill:
    description: Suicide.
    aliases: [suicide, killme]
  tps:
    description: Shows server TPS.
    aliases: [servertps]
  queue:
    description: Shows players priority in queue.
    aliases: [queuepriority, priority]
  info:
    description: Shows info about server.
    aliases: [serverinfo, serverstats, serverstatistics]
  togglechat:
    description: Toggles the chat
    aliases: [chattoggle]
permissions:
  AnarchyCORE.*:
    children:
      AnarchyCORE.kill: true
      AnarchyCORE.killSomeone: true
      AnarchyCORE.tps: true
      AnarchyCORE.version: true
      AnarchyCORE.adminhelp: true
      AnarchyCORE.help: true
      AnarchyCORE.reload: true
      AnarchyCORE.togglechat: true
      AnarchyCORE.mutechat: true
      AnarchyCORE.slowchat: true
      AnarchyCOREQueue.admin: true
    default: false
  AnarchyCORE.regular:
    children:
      AnarchyCORE.kill: true
      AnarchyCORE.tps: true
      AnarchyCORE.version: true
      AnarchyCORE.togglechat: true
      AnarchyCORE.help: true
      AnarchyCOREQueue.regular: true
    default: true
  AnarchyCORE.priority:
    children:
      AnarchyCORE.kill: true
      AnarchyCORE.tps: true
      AnarchyCORE.version: true
      AnarchyCORE.help: true
      AnarchyCOREQueue.priority: true
    default: false
  AnarchyCORE.togglechat:
    description: Allows player to use /chattoggle.
  AnarchyCORE.mutechat:
    description: Allows player to use /chat mute.
  AnarchyCORE.slowchat:
    description: Allows player to use /chat slow.
  AnarchyCORE.help:
    description: Allows player to use /acore help.
    default: true
  AnarchyCORE.adminhelp:
    description: Allows player to use better /acore help.
    default: op
  AnarchyCORE.version:
    description: Allows player to use /acore version.
    default: true
  AnarchyCORE.reload:
    description: Allows player to reload the plugin.
    default: false
  AnarchyCORE.kill:
    description: Allows player to use /kill or /suicide.
    default: true
  AnarchyCORE.killSomeone:
    description: Allows player to use /kill on someone else.
    default: false
  AnarchyCORE.tps:
    description: Allows player to use /tps.
    default: true
  AnarchyCORE.queue.regular:
    description: Sets player priority level in queue.
    default: true
  AnarchyCORE.queue.priority:
    description: Sets player priority level in queue.
    default: false
  AnarchyCORE.queue.admin:
    description: Sets player priority level in queue.
    default: false