# ==================================== #
# -------------< CONFIG >------------- #
#                                      #
# AnarchyCORE - by Vesek and Matejko06 #
# VERSION 1.3.1                        #
# ==================================== #
# TPS color is from amount up to next color. #
tps-green: 16.00
tps-green-color: "&a&l"
tps-yellow: 8.00
tps-yellow-color: "&e&l"
tps-red-color: "&c&l"
# Queue priorities. #
regular-priority: "&7&lRegular"
priority-priority: "&6&lPriority"
admin-priority: "&c&lAdmin"
# If false, commands needs to set /tps and /help to /anarchycore:tps and /anarchycore:help in commands.yml. #
command-preprocessing:  true

# ==================================== #
# ------------< MESSAGES >------------ #
#                                      #
# AnarchyCORE - by Vesek and Matejko06 #
# VERSION 1.3.1                        #
# ==================================== #
# Help command #
help-message: "&3<----------------------->\n&6&o/help &3- Shows this.\n&6&o/kill &3- Kills the player.\n&6&o/tps &3- Shows server TPS.\n&6&o/info &3- Shows some info about the server.\n&6&o/priority &3or &3- Shows players queue priority.\n&3<----------------------->"
# Invalid command message. #
invalid-command-message: "&4This command does not exist! Use &6/help&4 for help."
# TPS message. #
tps-message: "&6Server TPS is: "
# Queue priority messages. #
queue-priority-message: "&6Your queue priority is: "
#Message for /info #
info-message: "&3Already <players> players have connected to the server, server runs for <time> and world has <size> so far."
# Join message #
Player:
  JoinMessage: "has joined!"
# Leave message #
leave-message: "has left!"

# ==================================== #
# ---------< DEATH MESSAGES >--------- #
#                                      #
# AnarchyCORE - by Vesek and Matejko06 #
# VERSION 1.3.1                        #
# ==================================== #
suicide-message: "&4You killed yourself&4."
killedbyadmin-message: "&4You were killed&4."